#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const SRC_DIR = path.resolve(__dirname, "src");
const APP_DIR = path.resolve(__dirname, "app");
const OUTPUT_DIR = path.resolve(__dirname, "output");
const MARKER = "// @generated by purescript-rsc — do not edit";

// --- Scan PureScript sources ---

function findPursFiles(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...findPursFiles(full));
    else if (entry.name.endsWith(".purs")) results.push(full);
  }
  return results;
}

function detectDirective(mod, src) {
  if (/^--\s*@client\b/m.test(src)) return "use client";
  if (/^--\s*@server\b/m.test(src)) return "use server";
  if (/\.Client$/.test(mod)) return "use client";
  if (/\.Server$/.test(mod) || /^Actions\./.test(mod)) return "use server";
  return null;
}

function scanModules() {
  const modules = new Map();
  for (const file of findPursFiles(SRC_DIR)) {
    const src = fs.readFileSync(file, "utf-8");
    const modMatch = src.match(/^module\s+([\w.]+)/m);
    if (!modMatch) continue;
    const name = modMatch[1];
    const directive = detectDirective(name, src);
    modules.set(name, { name, src, file, directive });
  }
  return modules;
}

// --- Stale output cleanup ---
// PureScript compiler doesn't remove output/ dirs for deleted modules.
// We diff output/ against src/ and remove anything that has no source.

function cleanStaleOutput(sourceModules) {
  if (!fs.existsSync(OUTPUT_DIR)) return;

  const outputDirs = fs.readdirSync(OUTPUT_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);

  // Each compiled module has corefn.json with a modulePath field:
  //   "src/Pages/Home.purs"   — our code
  //   ".spago/p/prelude-6.0.2/src/Prelude.purs" — library
  // A module is stale if it's ours (modulePath starts with "src/")
  // but the source file no longer exists on disk.

  let removed = 0;
  for (const dir of outputDirs) {
    const corefnPath = path.join(OUTPUT_DIR, dir, "corefn.json");
    if (!fs.existsSync(corefnPath)) continue;

    try {
      const corefn = JSON.parse(fs.readFileSync(corefnPath, "utf-8"));
      const modulePath = corefn.modulePath;
      if (!modulePath) continue;

      // Skip library modules
      if (!modulePath.startsWith("src/") && !modulePath.startsWith("src\\")) continue;

      // Check if the source file still exists
      const fullSourcePath = path.resolve(__dirname, modulePath);
      if (fs.existsSync(fullSourcePath)) continue;

      // Source is gone — remove stale output
      const full = path.join(OUTPUT_DIR, dir);
      fs.rmSync(full, { recursive: true, force: true });
      console.log(`[purescript-rsc] stale output removed: output/${dir}/ (source was ${modulePath})`);
      removed++;
    } catch {}
  }

  if (removed > 0) {
    console.log(`[purescript-rsc] Cleaned ${removed} stale output dir(s)`);
  }
}

// --- Route generation ---

// Pages.Home        -> app/page.tsx               (Home is the index)
// Pages.About       -> app/about/page.tsx
// Pages.Blog.Post   -> app/blog/post/page.tsx
// Pages.Blog.$Slug  -> app/blog/[slug]/page.tsx   ($ prefix = dynamic segment)
// Layouts.Root      -> app/layout.tsx              (Root is the root layout)
// Layouts.Dashboard -> app/dashboard/layout.tsx

function moduleToRoute(mod, directive) {
  const parts = mod.split(".");
  const kind = parts[0];

  if (kind !== "Page" && kind !== "Layout") return null;

  const type = kind === "Page" ? "page" : "layout";
  const segments = parts.slice(1);

  const isIndex = segments.length === 1 && (segments[0] === "Home" || segments[0] === "Root");

  const routeSegments = isIndex
    ? []
    : segments.map((s) => {
        if (s.startsWith("$")) return "[" + s.slice(1).toLowerCase() + "]";
        return s.toLowerCase();
      });

  const routePath = path.join(APP_DIR, ...routeSegments);
  const filePath = path.join(routePath, `${type}.tsx`);
  const outputModule = `${OUTPUT_DIR}/${mod}/index.js`;
  const relImport = path.relative(routePath, outputModule).replace(/\\/g, "/");

  return { mod, type, filePath, relImport, routePath, directive };
}

function generateFile(route) {
  const lines = [];
  if (route.directive) lines.push(`"${route.directive}";`);
  lines.push(MARKER);
  const exportName = route.type;
  lines.push(
    `// @ts-expect-error — PureScript output`,
    `import { ${exportName} as mk } from "${route.relImport}";`,
  );
  if (route.directive === "use client") {
    lines.push(`export default mk();`);
  } else {
    // Server components can be async — await Aff/Promise results
    // Next.js 15 passes params and searchParams as Promises
    if (route.type === "page") {
      lines.push(
        `export default async function(props) {`,
        `  const render = await mk();`,
        `  const params = await (props.params ?? {});`,
        `  const searchParams = await (props.searchParams ?? {});`,
        `  return render({ params, searchParams });`,
        `}`,
      );
    } else {
      lines.push(
        `export default async function(props) {`,
        `  const render = await mk();`,
        `  return render(props);`,
        `}`,
      );
    }
  }
  lines.push("");
  return lines.join("\n");
}

// --- Clean stale generated route files ---
// Remove generated .tsx files whose source module no longer exists,
// then prune empty directories.

function cleanStaleRoutes(currentRoutes) {
  const currentPaths = new Set(currentRoutes.map((r) => r.filePath));
  removeStaleIn(APP_DIR, currentPaths);
}

function removeStaleIn(dir, keepPaths) {
  if (!fs.existsSync(dir)) return;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      removeStaleIn(full, keepPaths);
    } else if (entry.name.endsWith(".tsx")) {
      const content = fs.readFileSync(full, "utf-8");
      if (content.includes(MARKER) && !keepPaths.has(full)) {
        fs.unlinkSync(full);
        console.log(`[purescript-rsc] stale route removed: ${path.relative(process.cwd(), full)}`);
      }
    }
  }

  // Prune empty directories (but not app/ itself)
  try {
    if (fs.readdirSync(dir).length === 0 && dir !== APP_DIR) {
      fs.rmdirSync(dir);
      console.log(`[purescript-rsc] pruned empty dir: ${path.relative(process.cwd(), dir)}/`);
    }
  } catch {}
}

// --- Write routes (skip unchanged) ---

function writeRoute(route) {
  const content = generateFile(route);
  fs.mkdirSync(route.routePath, { recursive: true });

  // Skip write if file already has the exact same content
  if (fs.existsSync(route.filePath)) {
    const existing = fs.readFileSync(route.filePath, "utf-8");
    if (existing === content) return false;
  }

  fs.writeFileSync(route.filePath, content);
  return true;
}

// --- Route module codegen ---
// Generates src/Route.purs with a sum type for all page routes.

const PURS_MARKER = "-- @generated by purescript-rsc -- do not edit";

function generateRouteModule(routes) {
  const pageRoutes = routes.filter((r) => r.type === "page");

  const constructors = [];
  const cases = [];

  for (const route of pageRoutes) {
    const parts = route.mod.split(".").slice(1); // strip "Page"
    const isIndex = parts.length === 1 && parts[0] === "Home";
    const hasDynamic = parts.some((p) => p.startsWith("$"));

    const name = isIndex
      ? "Home"
      : parts.map((p) => (p.startsWith("$") ? p.slice(1) : p)).join("__");

    if (!hasDynamic) {
      constructors.push(name);
      const routePath = isIndex
        ? "/"
        : "/" + parts.map((p) => p.toLowerCase()).join("/");
      cases.push(`  ${name} -> "${routePath}"`);
    } else {
      const dynamicCount = parts.filter((p) => p.startsWith("$")).length;
      constructors.push(`${name}${" String".repeat(dynamicCount)}`);

      let varIdx = 0;
      const vars = [];
      const segments = [];
      for (const part of parts) {
        if (part.startsWith("$")) {
          const v = String.fromCharCode(97 + varIdx++);
          vars.push(v);
          segments.push({ dynamic: v });
        } else {
          segments.push({ static: part.toLowerCase() });
        }
      }

      const exprParts = segments.map((seg) =>
        seg.static !== undefined ? `"/${seg.static}"` : `"/" <> ${seg.dynamic}`,
      );
      const pathExpr = exprParts.join(" <> ");

      cases.push(`  ${name} ${vars.join(" ")} -> ${pathExpr}`);
    }
  }

  const content = [
    PURS_MARKER,
    "module Route where",
    "",
    "import Prelude",
    "",
    `data Route = ${constructors.join(" | ")}`,
    "",
    "derive instance Eq Route",
    "derive instance Ord Route",
    "",
    "toPath :: Route -> String",
    "toPath = case _ of",
    ...cases,
    "",
  ].join("\n");

  const filePath = path.join(SRC_DIR, "Route.purs");
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf-8");
    if (existing === content) {
      console.log("[purescript-rsc] Route.purs unchanged");
      return;
    }
  }

  fs.writeFileSync(filePath, content);
  console.log("[purescript-rsc] Generated src/Route.purs");
}

// --- Main ---

function main() {
  const sourceModules = scanModules();

  // 1. Clean stale output directories
  cleanStaleOutput(sourceModules);

  // 2. Compute desired routes from current sources
  const routes = [...sourceModules.values()]
    .map((m) => moduleToRoute(m.name, m.directive))
    .filter(Boolean);

  // 3. Generate Route.purs sum type
  generateRouteModule(routes);

  // 4. Remove stale generated route files
  cleanStaleRoutes(routes);

  // 5. Write/update route files
  let written = 0;
  let skipped = 0;
  for (const route of routes) {
    if (writeRoute(route)) {
      console.log(`[purescript-rsc] ${route.mod} -> ${path.relative(process.cwd(), route.filePath)}`);
      written++;
    } else {
      skipped++;
    }
  }

  console.log(
    `[purescript-rsc] ${written} written, ${skipped} unchanged, ${routes.length} total route(s)`
  );
}

main();
