#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const SRC_DIR = path.resolve(__dirname, "src");
const APP_DIR = path.resolve(__dirname, "app");
const OUTPUT_DIR = path.resolve(__dirname, "output");
const MARKER = "// @generated by purescript-rsc — do not edit";

// --- Scan PureScript sources ---

function findPursFiles(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...findPursFiles(full));
    else if (entry.name.endsWith(".purs")) results.push(full);
  }
  return results;
}

function detectDirective(mod, src) {
  if (/^--\s*@client\b/m.test(src)) return "use client";
  if (/^--\s*@server\b/m.test(src)) return "use server";
  if (/\.Client$/.test(mod)) return "use client";
  if (/\.Server$/.test(mod) || /^Actions\./.test(mod)) return "use server";
  return null;
}

function scanModules() {
  const modules = new Map();
  for (const file of findPursFiles(SRC_DIR)) {
    const src = fs.readFileSync(file, "utf-8");
    const modMatch = src.match(/^module\s+([\w.]+)/m);
    if (!modMatch) continue;
    const name = modMatch[1];
    const directive = detectDirective(name, src);
    modules.set(name, { name, src, file, directive });
  }
  return modules;
}

// --- Stale output cleanup ---
// PureScript compiler doesn't remove output/ dirs for deleted modules.
// We diff output/ against src/ and remove anything that has no source.

function cleanStaleOutput(sourceModules) {
  if (!fs.existsSync(OUTPUT_DIR)) return;

  const outputDirs = fs.readdirSync(OUTPUT_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);

  // Each compiled module has corefn.json with a modulePath field:
  //   "src/Pages/Home.purs"   — our code
  //   ".spago/p/prelude-6.0.2/src/Prelude.purs" — library
  // A module is stale if it's ours (modulePath starts with "src/")
  // but the source file no longer exists on disk.

  let removed = 0;
  for (const dir of outputDirs) {
    const corefnPath = path.join(OUTPUT_DIR, dir, "corefn.json");
    if (!fs.existsSync(corefnPath)) continue;

    try {
      const corefn = JSON.parse(fs.readFileSync(corefnPath, "utf-8"));
      const modulePath = corefn.modulePath;
      if (!modulePath) continue;

      // Skip library modules
      if (!modulePath.startsWith("src/") && !modulePath.startsWith("src\\")) continue;

      // Check if the source file still exists
      const fullSourcePath = path.resolve(__dirname, modulePath);
      if (fs.existsSync(fullSourcePath)) continue;

      // Source is gone — remove stale output
      const full = path.join(OUTPUT_DIR, dir);
      fs.rmSync(full, { recursive: true, force: true });
      console.log(`[purescript-rsc] stale output removed: output/${dir}/ (source was ${modulePath})`);
      removed++;
    } catch {}
  }

  if (removed > 0) {
    console.log(`[purescript-rsc] Cleaned ${removed} stale output dir(s)`);
  }
}

// --- Route generation ---

// Pages.Home        -> app/page.tsx               (Home is the index)
// Pages.About       -> app/about/page.tsx
// Pages.Blog.Post   -> app/blog/post/page.tsx
// Pages.Blog.$Slug  -> app/blog/[slug]/page.tsx   ($ prefix = dynamic segment)
// Layouts.Root      -> app/layout.tsx              (Root is the root layout)
// Layouts.Dashboard -> app/dashboard/layout.tsx

function moduleToRoute(mod, directive) {
  const parts = mod.split(".");
  const kind = parts[0];

  if (kind !== "Pages" && kind !== "Layouts") return null;

  const type = kind === "Pages" ? "page" : "layout";
  const segments = parts.slice(1);

  const isIndex = segments.length === 1 && (segments[0] === "Home" || segments[0] === "Root");

  const routeSegments = isIndex
    ? []
    : segments.map((s) => {
        if (s.startsWith("$")) return "[" + s.slice(1).toLowerCase() + "]";
        return s.toLowerCase();
      });

  const routePath = path.join(APP_DIR, ...routeSegments);
  const filePath = path.join(routePath, `${type}.tsx`);
  const outputModule = `${OUTPUT_DIR}/${mod}/index.js`;
  const relImport = path.relative(routePath, outputModule).replace(/\\/g, "/");

  return { mod, type, filePath, relImport, routePath, directive };
}

function generateFile(route) {
  const lines = [MARKER];
  if (route.directive) lines.push(`"${route.directive}";`);
  const exportName = route.type;
  lines.push(
    `// @ts-expect-error — PureScript output`,
    `import { ${exportName} as mk } from "${route.relImport}";`,
    `export default mk();`,
    ""
  );
  return lines.join("\n");
}

// --- Clean stale generated route files ---
// Remove generated .tsx files whose source module no longer exists,
// then prune empty directories.

function cleanStaleRoutes(currentRoutes) {
  const currentPaths = new Set(currentRoutes.map((r) => r.filePath));
  removeStaleIn(APP_DIR, currentPaths);
}

function removeStaleIn(dir, keepPaths) {
  if (!fs.existsSync(dir)) return;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      removeStaleIn(full, keepPaths);
    } else if (entry.name.endsWith(".tsx")) {
      const content = fs.readFileSync(full, "utf-8");
      if (content.startsWith(MARKER) && !keepPaths.has(full)) {
        fs.unlinkSync(full);
        console.log(`[purescript-rsc] stale route removed: ${path.relative(process.cwd(), full)}`);
      }
    }
  }

  // Prune empty directories (but not app/ itself)
  try {
    if (fs.readdirSync(dir).length === 0 && dir !== APP_DIR) {
      fs.rmdirSync(dir);
      console.log(`[purescript-rsc] pruned empty dir: ${path.relative(process.cwd(), dir)}/`);
    }
  } catch {}
}

// --- Write routes (skip unchanged) ---

function writeRoute(route) {
  const content = generateFile(route);
  fs.mkdirSync(route.routePath, { recursive: true });

  // Skip write if file already has the exact same content
  if (fs.existsSync(route.filePath)) {
    const existing = fs.readFileSync(route.filePath, "utf-8");
    if (existing === content) return false;
  }

  fs.writeFileSync(route.filePath, content);
  return true;
}

// --- Main ---

function main() {
  const sourceModules = scanModules();

  // 1. Clean stale output directories
  cleanStaleOutput(sourceModules);

  // 2. Compute desired routes from current sources
  const routes = [...sourceModules.values()]
    .map((m) => moduleToRoute(m.name, m.directive))
    .filter(Boolean);

  // 3. Remove stale generated route files
  cleanStaleRoutes(routes);

  // 4. Write/update route files
  let written = 0;
  let skipped = 0;
  for (const route of routes) {
    if (writeRoute(route)) {
      console.log(`[purescript-rsc] ${route.mod} -> ${path.relative(process.cwd(), route.filePath)}`);
      written++;
    } else {
      skipped++;
    }
  }

  console.log(
    `[purescript-rsc] ${written} written, ${skipped} unchanged, ${routes.length} total route(s)`
  );
}

main();
