"use client";
// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { page } from "../../output/Page.Actions/index.js";
import { use } from "react";
export default function(props) { return use(page(props)); }
