module Test.Loader where

import Prelude

import Data.Maybe (Maybe(..))
import Data.String as String
import Loader.Main (Segment(..), detectDirective, extractModuleName, generateTsx, kindToDeclName, kindToFileName, segmentsToNextPath)
import Loader.Plugin as Plugin
import Effect.Aff (Aff)
import ViTest (describe, test, viTest)
import ViTest.Expect (expectToSatisfy, (===))

main :: Unit
main = viTest do

  describe "detectDirective" do
    test "comment @client" do
      detectDirective "Foo" "module Foo where\n-- @client\nimport Prelude" === Just "use client"
    test "comment @server" do
      detectDirective "Foo" "module Foo where\n-- @server\nimport Prelude" === Just "use server"
    test "convention .Client suffix" do
      detectDirective "Page.Home.Client" "" === Just "use client"
    test "convention .Server suffix" do
      detectDirective "Page.Home.Server" "" === Just "use server"
    test "convention Actions. prefix" do
      detectDirective "Actions.Login" "" === Just "use server"
    test "no directive" do
      detectDirective "Page.Home" "module Page.Home where\nimport Prelude" === Nothing

  describe "extractModuleName" do
    test "simple module" do
      extractModuleName "module Foo.Bar where\n" === Just "Foo.Bar"
    test "module with exports" do
      extractModuleName "module Foo.Bar (baz) where\n" === Just "Foo.Bar"
    test "no module declaration" do
      extractModuleName "just some random text" === Nothing

  describe "segmentsToNextPath" do
    test "static" do
      segmentsToNextPath [ Static "blog" ] === [ "blog" ]
    test "dynamic" do
      segmentsToNextPath [ Dynamic "slug" ] === [ "[slug]" ]
    test "catch-all" do
      segmentsToNextPath [ CatchAll "slug" ] === [ "[...slug]" ]
    test "optional catch-all" do
      segmentsToNextPath [ OptCatchAll "slug" ] === [ "[[...slug]]" ]
    test "mixed segments" do
      segmentsToNextPath [ Static "blog", Dynamic "id" ] === [ "blog", "[id]" ]

  describe "kindToFileName" do
    test "notFound" do kindToFileName "notFound" === "not-found"
    test "page" do kindToFileName "page" === "page"
    test "layout" do kindToFileName "layout" === "layout"
    test "error" do kindToFileName "error" === "error"
    test "loading" do kindToFileName "loading" === "loading"

  describe "kindToDeclName" do
    test "error" do kindToDeclName "error" === "error"
    test "page" do kindToDeclName "page" === "page"
    test "layout" do kindToDeclName "layout" === "layout"
    test "notFound" do kindToDeclName "notFound" === "notFound"

  describe "generateTsx" do
    test "client gets use client directive" do
      clientTsx `shouldContain` (show "use client" <> ";")
    test "client awaits mk()" do
      clientTsx `shouldContain` "await mk()"
    test "server page is async" do
      serverPageTsx `shouldContain` "async function(props)"
    test "server page awaits params" do
      serverPageTsx `shouldContain` "await (props.params"
    test "server page awaits searchParams" do
      serverPageTsx `shouldContain` "await (props.searchParams"
    test "server page has no use client" do
      serverPageTsx `shouldNotContain` show "use client"
    test "layout renders props" do
      layoutTsx `shouldContain` "render(props)"
    test "layout has no params" do
      layoutTsx `shouldNotContain` "params"
    test "error gets use client" do
      errorTsx `shouldContain` (show "use client" <> ";")
    test "loading renders without args" do
      loadingTsx `shouldContain` "render()"
    test "loading has no props" do
      loadingTsx `shouldNotContain` "props"
    test "notFound renders without args" do
      notFoundTsx `shouldContain` "render()"
    test "has generator marker" do
      serverPageTsx `shouldContain` "@generated by purescript-rsc"
    test "import path is correct" do
      fooTsx `shouldContain` show "../output/Page.Foo/index.js"

  describe "extractModule" do
    test "unix path" do
      Plugin.extractModule "/project/output/Page.Home/index.js" === Just "Page.Home"
    test "windows path" do
      Plugin.extractModule "C:\\project\\output\\Page.Home\\index.js" === Just "Page.Home"
    test "non-matching path" do
      Plugin.extractModule "/some/random/file.js" === Nothing
    test "dotted module name" do
      Plugin.extractModule "/project/output/Page.Blog.Slug/index.js" === Just "Page.Blog.Slug"

  where
  route kind directive =
    { mod: "Page.Home"
    , kind
    , filePath: "app/page.tsx"
    , relImport: "../output/Page.Home/index.js"
    , routePath: "app"
    , directive
    }
  clientTsx = generateTsx (route "page" (Just "use client"))
  serverPageTsx = generateTsx (route "page" Nothing)
  layoutTsx = generateTsx
    { mod: "Layout.Root", kind: "layout", filePath: "app/layout.tsx"
    , relImport: "../output/Layout.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  errorTsx = generateTsx
    { mod: "ErrorBoundary.Root", kind: "error", filePath: "app/error.tsx"
    , relImport: "../output/ErrorBoundary.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  loadingTsx = generateTsx
    { mod: "Loading.Root", kind: "loading", filePath: "app/loading.tsx"
    , relImport: "../output/Loading.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  notFoundTsx = generateTsx
    { mod: "NotFound.Root", kind: "notFound", filePath: "app/not-found.tsx"
    , relImport: "../output/NotFound.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  fooTsx = generateTsx
    { mod: "Page.Foo", kind: "page", filePath: "app/foo/page.tsx"
    , relImport: "../output/Page.Foo/index.js", routePath: "app/foo"
    , directive: Nothing
    }

shouldContain :: String -> String -> Aff Unit
shouldContain haystack needle =
  expectToSatisfy haystack (String.contains (String.Pattern needle))

shouldNotContain :: String -> String -> Aff Unit
shouldNotContain haystack needle =
  expectToSatisfy haystack (not <<< String.contains (String.Pattern needle))
