module Test.Loader where

import Prelude

import Data.Maybe (Maybe(..))
import Data.String as String
import Effect (Effect)
import Effect.Console as Console
import Loader.Main (Segment(..), detectDirective, extractModuleName, generateTsx, kindToDeclName, kindToFileName, segmentsToNextPath)
import Loader.Plugin as Plugin
import Test.Assert (assertEqual, assertTrue', assertFalse')

main :: Effect Unit
main = do
  testDetectDirective
  testExtractModuleName
  testSegmentsToNextPath
  testKindToFileName
  testKindToDeclName
  testGenerateTsx
  testExtractModule
  Console.log "All loader tests passed!"

--------------------------------------------------------------------------------
-- detectDirective
--------------------------------------------------------------------------------

testDetectDirective :: Effect Unit
testDetectDirective = do
  assertEqual
    { actual: detectDirective "Foo" "module Foo where\n-- @client\nimport Prelude"
    , expected: Just "use client"
    }
  assertEqual
    { actual: detectDirective "Foo" "module Foo where\n-- @server\nimport Prelude"
    , expected: Just "use server"
    }
  assertEqual
    { actual: detectDirective "Page.Home.Client" ""
    , expected: Just "use client"
    }
  assertEqual
    { actual: detectDirective "Page.Home.Server" ""
    , expected: Just "use server"
    }
  assertEqual
    { actual: detectDirective "Actions.Login" ""
    , expected: Just "use server"
    }
  assertEqual
    { actual: detectDirective "Page.Home" "module Page.Home where\nimport Prelude"
    , expected: Nothing
    }

--------------------------------------------------------------------------------
-- extractModuleName
--------------------------------------------------------------------------------

testExtractModuleName :: Effect Unit
testExtractModuleName = do
  assertEqual
    { actual: extractModuleName "module Foo.Bar where\n"
    , expected: Just "Foo.Bar"
    }
  assertEqual
    { actual: extractModuleName "module Foo.Bar (baz) where\n"
    , expected: Just "Foo.Bar"
    }
  assertEqual
    { actual: extractModuleName "just some random text"
    , expected: Nothing
    }

--------------------------------------------------------------------------------
-- segmentsToNextPath
--------------------------------------------------------------------------------

testSegmentsToNextPath :: Effect Unit
testSegmentsToNextPath = do
  assertEqual
    { actual: segmentsToNextPath [ Static "blog" ]
    , expected: [ "blog" ]
    }
  assertEqual
    { actual: segmentsToNextPath [ Dynamic "slug" ]
    , expected: [ "[slug]" ]
    }
  assertEqual
    { actual: segmentsToNextPath [ CatchAll "slug" ]
    , expected: [ "[...slug]" ]
    }
  assertEqual
    { actual: segmentsToNextPath [ OptCatchAll "slug" ]
    , expected: [ "[[...slug]]" ]
    }
  assertEqual
    { actual: segmentsToNextPath [ Static "blog", Dynamic "id" ]
    , expected: [ "blog", "[id]" ]
    }

--------------------------------------------------------------------------------
-- kindToFileName
--------------------------------------------------------------------------------

testKindToFileName :: Effect Unit
testKindToFileName = do
  assertEqual { actual: kindToFileName "notFound", expected: "not-found" }
  assertEqual { actual: kindToFileName "page", expected: "page" }
  assertEqual { actual: kindToFileName "layout", expected: "layout" }
  assertEqual { actual: kindToFileName "error", expected: "error" }
  assertEqual { actual: kindToFileName "loading", expected: "loading" }

--------------------------------------------------------------------------------
-- kindToDeclName
--------------------------------------------------------------------------------

testKindToDeclName :: Effect Unit
testKindToDeclName = do
  assertEqual { actual: kindToDeclName "error", expected: "error" }
  assertEqual { actual: kindToDeclName "page", expected: "page" }
  assertEqual { actual: kindToDeclName "layout", expected: "layout" }
  assertEqual { actual: kindToDeclName "notFound", expected: "notFound" }

--------------------------------------------------------------------------------
-- generateTsx
--------------------------------------------------------------------------------

testGenerateTsx :: Effect Unit
testGenerateTsx = do
  clientTsx `shouldContain` (show "use client" <> ";")
  clientTsx `shouldContain` "await mk()"

  serverPageTsx `shouldContain` "async function(props)"
  serverPageTsx `shouldContain` "await (props.params"
  serverPageTsx `shouldContain` "await (props.searchParams"
  serverPageTsx `shouldNotContain` show "use client"

  layoutTsx `shouldContain` "render(props)"
  layoutTsx `shouldNotContain` "params"

  errorTsx `shouldContain` (show "use client" <> ";")

  loadingTsx `shouldContain` "render()"
  loadingTsx `shouldNotContain` "props"

  notFoundTsx `shouldContain` "render()"

  serverPageTsx `shouldContain` "@generated by purescript-rsc"

  fooTsx `shouldContain` show "../output/Page.Foo/index.js"
  where
  route kind directive =
    { mod: "Page.Home"
    , kind
    , filePath: "app/page.tsx"
    , relImport: "../output/Page.Home/index.js"
    , routePath: "app"
    , directive
    }
  clientTsx = generateTsx (route "page" (Just "use client"))
  serverPageTsx = generateTsx (route "page" Nothing)
  layoutTsx = generateTsx
    { mod: "Layout.Root", kind: "layout", filePath: "app/layout.tsx"
    , relImport: "../output/Layout.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  errorTsx = generateTsx
    { mod: "ErrorBoundary.Root", kind: "error", filePath: "app/error.tsx"
    , relImport: "../output/ErrorBoundary.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  loadingTsx = generateTsx
    { mod: "Loading.Root", kind: "loading", filePath: "app/loading.tsx"
    , relImport: "../output/Loading.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  notFoundTsx = generateTsx
    { mod: "NotFound.Root", kind: "notFound", filePath: "app/not-found.tsx"
    , relImport: "../output/NotFound.Root/index.js", routePath: "app"
    , directive: Nothing
    }
  fooTsx = generateTsx
    { mod: "Page.Foo", kind: "page", filePath: "app/foo/page.tsx"
    , relImport: "../output/Page.Foo/index.js", routePath: "app/foo"
    , directive: Nothing
    }

--------------------------------------------------------------------------------
-- extractModule (Webpack loader)
--------------------------------------------------------------------------------

testExtractModule :: Effect Unit
testExtractModule = do
  assertEqual
    { actual: Plugin.extractModule "/project/output/Page.Home/index.js"
    , expected: Just "Page.Home"
    }
  assertEqual
    { actual: Plugin.extractModule "C:\\project\\output\\Page.Home\\index.js"
    , expected: Just "Page.Home"
    }
  assertEqual
    { actual: Plugin.extractModule "/some/random/file.js"
    , expected: Nothing
    }
  assertEqual
    { actual: Plugin.extractModule "/project/output/Page.Blog.Slug/index.js"
    , expected: Just "Page.Blog.Slug"
    }

--------------------------------------------------------------------------------
-- Helpers
--------------------------------------------------------------------------------

shouldContain :: String -> String -> Effect Unit
shouldContain haystack needle =
  assertTrue' ("expected to contain " <> show needle)
    (String.contains (String.Pattern needle) haystack)

shouldNotContain :: String -> String -> Effect Unit
shouldNotContain haystack needle =
  assertFalse' ("expected not to contain " <> show needle)
    (String.contains (String.Pattern needle) haystack)
