// Generated by purs version 0.15.15
import * as $foreign from "./foreign.js";
import * as Control_Applicative from "../Control.Applicative/index.js";
import * as Control_Bind from "../Control.Bind/index.js";
import * as Data_Array from "../Data.Array/index.js";
import * as Data_Array_NonEmpty_Internal from "../Data.Array.NonEmpty.Internal/index.js";
import * as Data_Boolean from "../Data.Boolean/index.js";
import * as Data_Eq from "../Data.Eq/index.js";
import * as Data_Foldable from "../Data.Foldable/index.js";
import * as Data_Functor from "../Data.Functor/index.js";
import * as Data_Map_Internal from "../Data.Map.Internal/index.js";
import * as Data_Maybe from "../Data.Maybe/index.js";
import * as Data_Monoid from "../Data.Monoid/index.js";
import * as Data_Ord from "../Data.Ord/index.js";
import * as Data_Semigroup from "../Data.Semigroup/index.js";
import * as Data_Show from "../Data.Show/index.js";
import * as Data_String_CodePoints from "../Data.String.CodePoints/index.js";
import * as Data_String_CodeUnits from "../Data.String.CodeUnits/index.js";
import * as Data_String_Common from "../Data.String.Common/index.js";
import * as Data_Tuple from "../Data.Tuple/index.js";
import * as Data_Unfoldable from "../Data.Unfoldable/index.js";
import * as Data_Unit from "../Data.Unit/index.js";
import * as Effect from "../Effect/index.js";
import * as Effect_Console from "../Effect.Console/index.js";
import * as PureScript_CST from "../PureScript.CST/index.js";
import * as PureScript_CST_Types from "../PureScript.CST.Types/index.js";
var show = /* #__PURE__ */ Data_Show.show(Data_Show.showString);
var eq = /* #__PURE__ */ Data_Eq.eq(Data_Eq.eqString);
var pure = /* #__PURE__ */ Control_Applicative.pure(Effect.applicativeEffect);
var map = /* #__PURE__ */ Data_Functor.map(Data_Maybe.functorMaybe);
var toUnfoldable = /* #__PURE__ */ Data_Map_Internal.toUnfoldable(Data_Unfoldable.unfoldableArray);
var when = /* #__PURE__ */ Control_Applicative.when(Effect.applicativeEffect);
var map1 = /* #__PURE__ */ Data_Functor.map(Data_Functor.functorArray);
var eq1 = /* #__PURE__ */ Data_Eq.eq(/* #__PURE__ */ Data_Maybe.eqMaybe(Data_Eq.eqChar));
var for_ = /* #__PURE__ */ Data_Foldable.for_(Effect.applicativeEffect)(Data_Foldable.foldableArray);
var elem = /* #__PURE__ */ Data_Array.elem(Data_Eq.eqString);
var append1 = /* #__PURE__ */ Data_Semigroup.append(Data_Semigroup.semigroupArray);
var fromFoldable = /* #__PURE__ */ Data_Array.fromFoldable(Data_Array_NonEmpty_Internal.foldableNonEmptyArray);
var eqMaybe = /* #__PURE__ */ Data_Maybe.eqMaybe(Data_Eq.eqString);
var eq2 = /* #__PURE__ */ Data_Eq.eq(eqMaybe);
var foldMap = /* #__PURE__ */ Data_Foldable.foldMap(Data_Foldable.foldableArray)(Data_Monoid.monoidString);
var map2 = /* #__PURE__ */ Data_Functor.map(Effect.functorEffect);
var bind1 = /* #__PURE__ */ Control_Bind.bind(Data_Maybe.bindMaybe);
var lookup = /* #__PURE__ */ Data_Map_Internal.lookup(Data_Ord.ordString);
var eq3 = /* #__PURE__ */ Data_Eq.eq(/* #__PURE__ */ Data_Eq.eqArray(Data_Eq.eqString));
var foldl = /* #__PURE__ */ Data_Foldable.foldl(Data_Foldable.foldableArray);
var notEq1 = /* #__PURE__ */ Data_Eq.notEq(eqMaybe);
var insert = /* #__PURE__ */ Data_Map_Internal.insert(Data_Ord.ordString);
var unless = /* #__PURE__ */ Control_Applicative.unless(Effect.applicativeEffect);
var show1 = /* #__PURE__ */ Data_Show.show(Data_Show.showInt);
var Static = /* #__PURE__ */ (function () {
    function Static(value0) {
        this.value0 = value0;
    };
    Static.create = function (value0) {
        return new Static(value0);
    };
    return Static;
})();
var Dynamic = /* #__PURE__ */ (function () {
    function Dynamic(value0) {
        this.value0 = value0;
    };
    Dynamic.create = function (value0) {
        return new Dynamic(value0);
    };
    return Dynamic;
})();
var CatchAll = /* #__PURE__ */ (function () {
    function CatchAll(value0) {
        this.value0 = value0;
    };
    CatchAll.create = function (value0) {
        return new CatchAll(value0);
    };
    return CatchAll;
})();
var OptCatchAll = /* #__PURE__ */ (function () {
    function OptCatchAll(value0) {
        this.value0 = value0;
    };
    OptCatchAll.create = function (value0) {
        return new OptCatchAll(value0);
    };
    return OptCatchAll;
})();
var showSegment = {
    show: function (v) {
        if (v instanceof Static) {
            return "(Static " + (show(v.value0) + ")");
        };
        if (v instanceof Dynamic) {
            return "(Dynamic " + (show(v.value0) + ")");
        };
        if (v instanceof CatchAll) {
            return "(CatchAll " + (show(v.value0) + ")");
        };
        if (v instanceof OptCatchAll) {
            return "(OptCatchAll " + (show(v.value0) + ")");
        };
        throw new Error("Failed pattern match at Loader.Main (line 42, column 1 - line 46, column 58): " + [ v.constructor.name ]);
    }
};
var eqSegment = {
    eq: function (x) {
        return function (y) {
            if (x instanceof Static && y instanceof Static) {
                return x.value0 === y.value0;
            };
            if (x instanceof Dynamic && y instanceof Dynamic) {
                return x.value0 === y.value0;
            };
            if (x instanceof CatchAll && y instanceof CatchAll) {
                return x.value0 === y.value0;
            };
            if (x instanceof OptCatchAll && y instanceof OptCatchAll) {
                return x.value0 === y.value0;
            };
            return false;
        };
    }
};
var writeIfChanged = function (filePath) {
    return function (content) {
        return function __do() {
            var exists = $foreign.existsSync(filePath)();
            if (exists) {
                var existing = $foreign.readFileSync(filePath)();
                var $131 = existing === content;
                if ($131) {
                    return false;
                };
                $foreign.writeFileSync(filePath)(content)();
                return true;
            };
            $foreign.writeFileSync(filePath)(content)();
            return true;
        };
    };
};
var writeDirectivesManifest = function (outputDir) {
    return function (modules) {
        return function __do() {
            $foreign.mkdirSync(outputDir)();
            var entries = Data_Array.mapMaybe(function (v) {
                return map(function (d) {
                    return show(v.value0) + (": " + show(d));
                })(v.value1.directive);
            })(toUnfoldable(modules));
            var json = "{\x0a  " + (Data_String_Common.joinWith(",\x0a  ")(entries) + "\x0a}\x0a");
            var manifestPath = $foreign.joinPath(outputDir)("directives.json");
            var changed = writeIfChanged(manifestPath)(json)();
            return when(changed)(Effect_Console.log("[purescript-rsc] Updated output/directives.json"))();
        };
    };
};
var varNames = [ "a", "b", "c", "d", "e", "f" ];
var varName = function (i) {
    return Data_Maybe.fromMaybe("z")(Data_Array.index(varNames)(i));
};
var typeToSegment = function (v) {
    if (v instanceof PureScript_CST_Types.TypeString) {
        return new Static(v.value1);
    };
    return new Static("unknown");
};
var segmentsToNextPath = /* #__PURE__ */ map1(function (v) {
    if (v instanceof Static) {
        return v.value0;
    };
    if (v instanceof Dynamic) {
        return "[" + (v.value0 + "]");
    };
    if (v instanceof CatchAll) {
        return "[..." + (v.value0 + "]");
    };
    if (v instanceof OptCatchAll) {
        return "[[..." + (v.value0 + "]]");
    };
    throw new Error("Failed pattern match at Loader.Main (line 298, column 26 - line 302, column 40): " + [ v.constructor.name ]);
});
var routeConfigNames = [ "dynamic", "revalidate", "runtime", "preferredRegion", "maxDuration", "fetchCache" ];
var pursMarker = "-- @generated by purescript-rsc -- do not edit";
var modulePathSegments = function (parts) {
    var toSpecialDir = function (seg) {
        if (Data_String_Common["null"](seg)) {
            return Data_Maybe.Nothing.value;
        };
        if (seg === "Intercept_") {
            return new Data_Maybe.Just("(.)");
        };
        if (seg === "InterceptUp_") {
            return new Data_Maybe.Just("(..)");
        };
        if (seg === "InterceptRoot_") {
            return new Data_Maybe.Just("(...)");
        };
        if (eq1(Data_String_CodeUnits.charAt(Data_String_CodePoints.length(seg) - 1 | 0)(seg))(new Data_Maybe.Just("_"))) {
            return new Data_Maybe.Just("(" + (Data_String_Common.toLower(Data_String_CodePoints.take(Data_String_CodePoints.length(seg) - 1 | 0)(seg)) + ")"));
        };
        if (Data_Boolean.otherwise) {
            return Data_Maybe.Nothing.value;
        };
        throw new Error("Failed pattern match at Loader.Main (line 316, column 3 - line 323, column 26): " + [ seg.constructor.name ]);
    };
    return Data_Array.mapMaybe(toSpecialDir)(parts);
};
var methodToExportName = function (v) {
    if (v === "delete_") {
        return "DELETE";
    };
    if (v === "head_") {
        return "HEAD";
    };
    return Data_String_Common.toUpper(v);
};
var marker = "// @generated by purescript-rsc \u2014 do not edit";
var removeStaleIn = function (dir) {
    return function (keepPaths) {
        return function __do() {
            var exists = $foreign.existsSync(dir)();
            return when(exists)(function __do() {
                var entries = $foreign.readdirSync(dir)();
                for_(entries)(function (entry) {
                    var full = $foreign.joinPath(dir)(entry.name);
                    if (entry.isDirectory) {
                        return removeStaleIn(full)(keepPaths);
                    };
                    return when(Data_String_CodeUnits.contains(".tsx")(entry.name) || Data_String_CodeUnits.contains(".ts")(entry.name))(function __do() {
                        var content = $foreign.readFileSync(full)();
                        return when(Data_String_CodeUnits.contains(marker)(content) && !elem(full)(keepPaths))(function __do() {
                            $foreign.unlinkSync(full)();
                            return Effect_Console.log("[purescript-rsc] stale route removed: " + full)();
                        })();
                    });
                })();
                var remaining = $foreign.readdirSync(dir)();
                return when(Data_Array["null"](remaining))($foreign.rmSync(dir))();
            })();
        };
    };
};
var markLastOptCatchAll = function (segs) {
    var v = Data_Array.unsnoc(segs);
    if (v instanceof Data_Maybe.Just && v.value0.last instanceof Static) {
        return append1(v.value0.init)([ new OptCatchAll(v.value0.last.value0) ]);
    };
    return segs;
};
var markLastDynamic = function (segs) {
    var v = Data_Array.unsnoc(segs);
    if (v instanceof Data_Maybe.Just && v.value0.last instanceof Static) {
        return append1(v.value0.init)([ new Dynamic(v.value0.last.value0) ]);
    };
    return segs;
};
var markLastCatchAll = function (segs) {
    var v = Data_Array.unsnoc(segs);
    if (v instanceof Data_Maybe.Just && v.value0.last instanceof Static) {
        return append1(v.value0.init)([ new CatchAll(v.value0.last.value0) ]);
    };
    return segs;
};
var walkOpChain = function (head) {
    return function (ops) {
        var go = function ($copy_acc) {
            return function ($copy_arr) {
                var $tco_var_acc = $copy_acc;
                var $tco_done = false;
                var $tco_result;
                function $tco_loop(acc, arr) {
                    var v = Data_Array.uncons(arr);
                    if (v instanceof Data_Maybe.Nothing) {
                        $tco_done = true;
                        return acc;
                    };
                    if (v instanceof Data_Maybe.Just) {
                        if (v.value0.head.value0.name === "/") {
                            $tco_var_acc = append1(acc)([ typeToSegment(v.value0.head.value1) ]);
                            $copy_arr = v.value0.tail;
                            return;
                        };
                        if (v.value0.head.value0.name === ":") {
                            $tco_var_acc = markLastDynamic(acc);
                            $copy_arr = v.value0.tail;
                            return;
                        };
                        if (v.value0.head.value0.name === ":..") {
                            $tco_var_acc = markLastCatchAll(acc);
                            $copy_arr = v.value0.tail;
                            return;
                        };
                        if (v.value0.head.value0.name === ":..?") {
                            $tco_var_acc = markLastOptCatchAll(acc);
                            $copy_arr = v.value0.tail;
                            return;
                        };
                        if (v.value0.head.value0.name === ":?") {
                            $tco_done = true;
                            return acc;
                        };
                        if (Data_Boolean.otherwise) {
                            $tco_var_acc = acc;
                            $copy_arr = v.value0.tail;
                            return;
                        };
                    };
                    throw new Error("Failed pattern match at Loader.Main (line 185, column 16 - line 193, column 33): " + [ v.constructor.name ]);
                };
                while (!$tco_done) {
                    $tco_result = $tco_loop($tco_var_acc, $copy_arr);
                };
                return $tco_result;
            };
        };
        return go([ typeToSegment(head) ])(ops);
    };
};
var walkTypeArg = function ($copy_v) {
    var $tco_done = false;
    var $tco_result;
    function $tco_loop(v) {
        if (v instanceof PureScript_CST_Types.TypeString) {
            $tco_done = true;
            return [ new Static(v.value1) ];
        };
        if (v instanceof PureScript_CST_Types.TypeParens) {
            $copy_v = v.value0.value;
            return;
        };
        if (v instanceof PureScript_CST_Types.TypeOp) {
            $tco_done = true;
            return walkOpChain(v.value0)(fromFoldable(v.value1));
        };
        if (v instanceof PureScript_CST_Types.TypeConstructor && v.value0.name === "Root") {
            $tco_done = true;
            return [  ];
        };
        $tco_done = true;
        return [  ];
    };
    while (!$tco_done) {
        $tco_result = $tco_loop($copy_v);
    };
    return $tco_result;
};
var layoutPathSegments = function (parts) {
    var toDir = function (seg) {
        if (Data_String_Common["null"](seg)) {
            return Data_Maybe.Nothing.value;
        };
        if (seg === "Root") {
            return Data_Maybe.Nothing.value;
        };
        if (seg === "Intercept_") {
            return new Data_Maybe.Just("(.)");
        };
        if (seg === "InterceptUp_") {
            return new Data_Maybe.Just("(..)");
        };
        if (seg === "InterceptRoot_") {
            return new Data_Maybe.Just("(...)");
        };
        if (eq1(Data_String_CodeUnits.charAt(Data_String_CodePoints.length(seg) - 1 | 0)(seg))(new Data_Maybe.Just("_"))) {
            return new Data_Maybe.Just("(" + (Data_String_Common.toLower(Data_String_CodePoints.take(Data_String_CodePoints.length(seg) - 1 | 0)(seg)) + ")"));
        };
        if (Data_Boolean.otherwise) {
            return new Data_Maybe.Just(Data_String_Common.toLower(seg));
        };
        throw new Error("Failed pattern match at Loader.Main (line 330, column 3 - line 338, column 44): " + [ seg.constructor.name ]);
    };
    return Data_Array.mapMaybe(toDir)(parts);
};
var kindToFileName = function (v) {
    if (v === "notFound") {
        return "not-found";
    };
    if (v === "globalError") {
        return "global-error";
    };
    if (v === "handler") {
        return "route";
    };
    return v;
};
var kindToDeclName = function (v) {
    if (v === "error") {
        return "error";
    };
    if (v === "globalError") {
        return "globalError";
    };
    if (v === "default") {
        return "default";
    };
    return v;
};
var isJsReserved = function (v) {
    if (v === "default") {
        return true;
    };
    if (v === "delete") {
        return true;
    };
    return false;
};
var hasViewportSig = function (v) {
    var matchVP = function (v1) {
        if (v1 instanceof PureScript_CST_Types.DeclSignature && v1.value0.label.name === "viewport") {
            return true;
        };
        return false;
    };
    return Data_Array.any(matchVP)(v.decls);
};
var hasViewportDecl = function (src) {
    var v = PureScript_CST.parseModule(src);
    if (v instanceof PureScript_CST.ParseSucceeded) {
        return hasViewportSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
        return hasViewportSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseFailed) {
        return false;
    };
    throw new Error("Failed pattern match at Loader.Main (line 242, column 23 - line 245, column 25): " + [ v.constructor.name ]);
};
var hasStaticParamsSig = function (v) {
    var matchSP = function (v1) {
        if (v1 instanceof PureScript_CST_Types.DeclSignature && v1.value0.label.name === "staticParams") {
            return true;
        };
        return false;
    };
    return Data_Array.any(matchSP)(v.decls);
};
var hasStaticParamsDecl = function (src) {
    var v = PureScript_CST.parseModule(src);
    if (v instanceof PureScript_CST.ParseSucceeded) {
        return hasStaticParamsSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
        return hasStaticParamsSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseFailed) {
        return false;
    };
    throw new Error("Failed pattern match at Loader.Main (line 229, column 27 - line 232, column 25): " + [ v.constructor.name ]);
};
var hasMetaSig = function (v) {
    var matchMeta = function (v1) {
        if (v1 instanceof PureScript_CST_Types.DeclSignature && v1.value0.label.name === "metadata") {
            return true;
        };
        return false;
    };
    return Data_Array.any(matchMeta)(v.decls);
};
var hasMetadataDecl = function (src) {
    var v = PureScript_CST.parseModule(src);
    if (v instanceof PureScript_CST.ParseSucceeded) {
        return hasMetaSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
        return hasMetaSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseFailed) {
        return false;
    };
    throw new Error("Failed pattern match at Loader.Main (line 216, column 23 - line 219, column 25): " + [ v.constructor.name ]);
};
var hasConfigSig = function (v) {
    var matchConfig = function (v1) {
        if (v1 instanceof PureScript_CST_Types.DeclSignature && v1.value0.label.name === "config") {
            return true;
        };
        return false;
    };
    return Data_Array.any(matchConfig)(v.decls);
};
var hasConfigDecl = function (src) {
    var v = PureScript_CST.parseModule(src);
    if (v instanceof PureScript_CST.ParseSucceeded) {
        return hasConfigSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
        return hasConfigSig(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseFailed) {
        return false;
    };
    throw new Error("Failed pattern match at Loader.Main (line 648, column 21 - line 651, column 25): " + [ v.constructor.name ]);
};
var handlerMethodNames = [ "get", "post", "put", "delete_", "patch", "head_", "options" ];
var generateTsx = function (route) {
    var viewportExport = (function () {
        if (route.hasViewport) {
            return ", viewport as generateViewport";
        };
        if (Data_Boolean.otherwise) {
            return "";
        };
        throw new Error("Failed pattern match at Loader.Main (line 468, column 3 - line 470, column 21): " + [  ]);
    })();
    var staticParamsExport = (function () {
        if (route.hasStaticParams) {
            return ", staticParams as generateStaticParams";
        };
        if (Data_Boolean.otherwise) {
            return "";
        };
        throw new Error("Failed pattern match at Loader.Main (line 472, column 3 - line 474, column 21): " + [  ]);
    })();
    var metadataExport = (function () {
        if (route.hasMetadata) {
            return ", metadata as generateMetadata";
        };
        if (Data_Boolean.otherwise) {
            return "";
        };
        throw new Error("Failed pattern match at Loader.Main (line 464, column 3 - line 466, column 21): " + [  ]);
    })();
    var isClient = eq2(route.directive)(new Data_Maybe.Just("use client")) || (route.kind === "error" || route.kind === "globalError");
    var handlerReExports = Data_String_Common.joinWith(", ")(map1(function (method) {
        return method + (" as " + methodToExportName(method));
    })(route.handlerMethods));
    var directiveLine = (function () {
        if (route.kind === "error" || route.kind === "globalError") {
            return [ show("use client") + ";" ];
        };
        if (Data_Boolean.otherwise) {
            if (route.directive instanceof Data_Maybe.Just) {
                return [ show(route.directive.value0) + ";" ];
            };
            if (route.directive instanceof Data_Maybe.Nothing) {
                return [  ];
            };
            throw new Error("Failed pattern match at Loader.Main (line 425, column 19 - line 427, column 22): " + [ route.directive.constructor.name ]);
        };
        throw new Error("Failed pattern match at Loader.Main (line 423, column 3 - line 427, column 22): " + [  ]);
    })();
    var declName = kindToDeclName(route.kind);
    var configReExports = foldMap(function (name) {
        return ", " + name;
    })(route.routeConfigs);
    var configExports = foldMap(function (name) {
        return ", " + name;
    })(route.routeConfigs);
    var contentLines = (function () {
        if (route.kind === "handler") {
            return [ marker, "// @ts-expect-error \u2014 PureScript output", "export { " + (handlerReExports + (configReExports + (" } from " + (show(route.relImport) + ";")))) ];
        };
        if (route.kind === "error" || route.kind === "globalError") {
            return [ marker, "// @ts-expect-error \u2014 PureScript output", "import { " + (declName + (" } from " + (show(route.relImport) + ";"))), "export default await " + (declName + "();") ];
        };
        if (isClient && (route.kind === "page" || route.kind === "default")) {
            var localName = (function () {
                var $227 = isJsReserved(declName);
                if ($227) {
                    return "_" + declName;
                };
                return declName;
            })();
            var importPart = (function () {
                var $228 = isJsReserved(declName);
                if ($228) {
                    return "import " + (localName + (" from " + (show(route.relImport) + ";")));
                };
                return "import { " + (declName + (" } from " + (show(route.relImport) + ";")));
            })();
            return [ marker, "// @ts-expect-error \u2014 PureScript output", importPart, "import { use } from \"react\";", "export default function(props) { return use(" + (localName + "(props)); }") ];
        };
        if (Data_Boolean.otherwise) {
            var defaultExport = (function () {
                var $229 = declName === "default";
                if ($229) {
                    return "default";
                };
                return declName + " as default";
            })();
            var extraExports = metadataExport + (viewportExport + (staticParamsExport + configExports));
            return [ marker, "// @ts-expect-error \u2014 PureScript output", "export { " + (defaultExport + (extraExports + (" } from " + (show(route.relImport) + ";")))) ];
        };
        throw new Error("Failed pattern match at Loader.Main (line 429, column 3 - line 462, column 10): " + [  ]);
    })();
    var lines = append1(directiveLine)(contentLines);
    return Data_String_Common.joinWith("\x0a")(append1(lines)([ "" ]));
};
var writeRouteFile = function (accEff) {
    return function (route) {
        return function __do() {
            var acc = accEff();
            $foreign.mkdirSync(route.routePath)();
            var content = generateTsx(route);
            var changed = writeIfChanged(route.filePath)(content)();
            if (changed) {
                Effect_Console.log("[purescript-rsc] " + (route.mod + (" -> " + route.filePath)))();
                return {
                    skipped: acc.skipped,
                    written: acc.written + 1 | 0
                };
            };
            return {
                written: acc.written,
                skipped: acc.skipped + 1 | 0
            };
        };
    };
};
var generateMiddleware = function (outputDir) {
    return function (info) {
        var outputModule = $foreign.joinPath(outputDir)(info.name + "/index.js");
        var relImport = $foreign.relativePath(".")(outputModule);
        var hasConfig = hasConfigDecl(info.source);
        var lines = [ marker, "// @ts-expect-error \u2014 PureScript output", "import { middleware" + ((function () {
            if (hasConfig) {
                return ", config";
            };
            return "";
        })() + (" } from " + (show(relImport) + ";"))), "export { middleware" + ((function () {
            if (hasConfig) {
                return ", config";
            };
            return "";
        })() + " };") ];
        return Data_String_Common.joinWith("\x0a")(append1(lines)([ "" ]));
    };
};
var findPursFiles = function (dir) {
    var traverse = function (f) {
        return function (xs) {
            var go = function (i) {
                return function (acc) {
                    if (i >= Data_Array.length(xs)) {
                        return pure(acc);
                    };
                    if (Data_Boolean.otherwise) {
                        var v = Data_Array.index(xs)(i);
                        if (v instanceof Data_Maybe.Nothing) {
                            return pure(acc);
                        };
                        if (v instanceof Data_Maybe.Just) {
                            return function __do() {
                                var r = f(v.value0)();
                                return go(i + 1 | 0)(append1(acc)([ r ]))();
                            };
                        };
                        throw new Error("Failed pattern match at Loader.Main (line 101, column 21 - line 105, column 38): " + [ v.constructor.name ]);
                    };
                    throw new Error("Failed pattern match at Loader.Main (line 99, column 5 - line 105, column 38): " + [ i.constructor.name, acc.constructor.name ]);
                };
            };
            return go(0)([  ]);
        };
    };
    var processEntry = function (entry) {
        if (entry.isDirectory) {
            return findPursFiles($foreign.joinPath(dir)(entry.name));
        };
        if (Data_String_CodeUnits.contains(".purs")(entry.name)) {
            return pure([ $foreign.joinPath(dir)(entry.name) ]);
        };
        if (Data_Boolean.otherwise) {
            return pure([  ]);
        };
        throw new Error("Failed pattern match at Loader.Main (line 91, column 3 - line 94, column 26): " + [ entry.constructor.name ]);
    };
    return function __do() {
        var exists = $foreign.existsSync(dir)();
        var $238 = !exists;
        if ($238) {
            return [  ];
        };
        var entries = $foreign.readdirSync(dir)();
        return map2(Data_Array.concat)(traverse(processEntry)(entries))();
    };
};
var findMethods = function (v) {
    var matchMethod = function (v1) {
        if (v1 instanceof PureScript_CST_Types.DeclSignature && elem(v1.value0.label.name)(handlerMethodNames)) {
            return new Data_Maybe.Just(v1.value0.label.name);
        };
        return Data_Maybe.Nothing.value;
    };
    return Data_Array.mapMaybe(matchMethod)(v.decls);
};
var findHandlerMethods = function (src) {
    var v = PureScript_CST.parseModule(src);
    if (v instanceof PureScript_CST.ParseSucceeded) {
        return findMethods(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
        return findMethods(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseFailed) {
        return [  ];
    };
    throw new Error("Failed pattern match at Loader.Main (line 258, column 26 - line 261, column 22): " + [ v.constructor.name ]);
};
var findConfigs = function (v) {
    var matchConfig = function (v1) {
        if (v1 instanceof PureScript_CST_Types.DeclSignature && elem(v1.value0.label.name)(routeConfigNames)) {
            return new Data_Maybe.Just(v1.value0.label.name);
        };
        return Data_Maybe.Nothing.value;
    };
    return Data_Array.mapMaybe(matchConfig)(v.decls);
};
var findRouteConfigDecls = function (src) {
    var v = PureScript_CST.parseModule(src);
    if (v instanceof PureScript_CST.ParseSucceeded) {
        return findConfigs(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
        return findConfigs(v.value0.body);
    };
    if (v instanceof PureScript_CST.ParseFailed) {
        return [  ];
    };
    throw new Error("Failed pattern match at Loader.Main (line 274, column 28 - line 277, column 22): " + [ v.constructor.name ]);
};
var extractModuleName = function (src) {
    var lines = Data_String_Common.split("\x0a")(src);
    return bind1(Data_Array.find(Data_String_CodeUnits.contains("module "))(lines))(function (line) {
        var trimmed = Data_String_Common.trim(line);
        var afterModule = Data_String_CodePoints.drop(7)(trimmed);
        var name = Data_String_CodeUnits.takeWhile(function (c) {
            return c !== " " && c !== "(";
        })(afterModule);
        var $261 = Data_String_CodePoints.length(name) > 0;
        if ($261) {
            return new Data_Maybe.Just(name);
        };
        return Data_Maybe.Nothing.value;
    });
};
var extractJsonField = function (field) {
    return function (json) {
        var max = function (v) {
            return function (v1) {
                if (v instanceof Data_Maybe.Nothing) {
                    return v1;
                };
                if (v1 instanceof Data_Maybe.Nothing) {
                    return v;
                };
                if (v instanceof Data_Maybe.Just && v1 instanceof Data_Maybe.Just) {
                    return new Data_Maybe.Just((function () {
                        var $264 = v.value0 > v1.value0;
                        if ($264) {
                            return v.value0;
                        };
                        return v1.value0;
                    })());
                };
                throw new Error("Failed pattern match at Loader.Main (line 562, column 3 - line 562, column 20): " + [ v.constructor.name, v1.constructor.name ]);
            };
        };
        var needle = show(field) + ":";
        var needle2 = show(field) + " :";
        var idx = max(Data_String_CodePoints.indexOf(needle)(json))(Data_String_CodePoints.indexOf(needle2)(json));
        if (idx instanceof Data_Maybe.Nothing) {
            return Data_Maybe.Nothing.value;
        };
        if (idx instanceof Data_Maybe.Just) {
            var rest = Data_String_CodePoints.drop((idx.value0 + Data_String_CodePoints.length(needle) | 0) + 1 | 0)(json);
            var trimmed = Data_String_Common.trim(rest);
            var $268 = eq1(Data_String_CodeUnits.charAt(0)(trimmed))(new Data_Maybe.Just("\""));
            if ($268) {
                var inner = Data_String_CodePoints.drop(1)(trimmed);
                var endIdx = Data_String_CodePoints.indexOf("\"")(inner);
                if (endIdx instanceof Data_Maybe.Just) {
                    return new Data_Maybe.Just(Data_String_CodePoints.take(endIdx.value0)(inner));
                };
                if (endIdx instanceof Data_Maybe.Nothing) {
                    return Data_Maybe.Nothing.value;
                };
                throw new Error("Failed pattern match at Loader.Main (line 557, column 9 - line 559, column 29): " + [ endIdx.constructor.name ]);
            };
            return Data_Maybe.Nothing.value;
        };
        throw new Error("Failed pattern match at Loader.Main (line 547, column 3 - line 560, column 19): " + [ idx.constructor.name ]);
    };
};
var extractFromType = function (v) {
    if (v instanceof PureScript_CST_Types.TypeApp) {
        if (v.value0 instanceof PureScript_CST_Types.TypeConstructor && (v.value0.value0.name === "Page" || (v.value0.value0.name === "Loading" || (v.value0.value0.name === "ErrorBoundary" || (v.value0.value0.name === "NotFound" || (v.value0.value0.name === "Template" || (v.value0.value0.name === "GlobalError" || (v.value0.value0.name === "Default" || (v.value0.value0.name === "Viewport" || (v.value0.value0.name === "Metadata" || (v.value0.value0.name === "GET" || (v.value0.value0.name === "POST" || (v.value0.value0.name === "PUT" || (v.value0.value0.name === "DELETE" || (v.value0.value0.name === "PATCH" || (v.value0.value0.name === "HEAD" || v.value0.value0.name === "OPTIONS")))))))))))))))) {
            var v1 = Data_Array.head(fromFoldable(v.value1));
            if (v1 instanceof Data_Maybe.Just) {
                return new Data_Maybe.Just(walkTypeArg(v1.value0));
            };
            if (v1 instanceof Data_Maybe.Nothing) {
                return Data_Maybe.Nothing.value;
            };
            throw new Error("Failed pattern match at Loader.Main (line 166, column 11 - line 168, column 31): " + [ v1.constructor.name ]);
        };
        return Data_Maybe.Nothing.value;
    };
    if (v instanceof PureScript_CST_Types.TypeConstructor && v.value0.name === "Layout") {
        return new Data_Maybe.Just([  ]);
    };
    return Data_Maybe.Nothing.value;
};
var findSignature = function (declName) {
    return function (v) {
        var matchDecl = function (v1) {
            if (v1 instanceof PureScript_CST_Types.DeclSignature && v1.value0.label.name === declName) {
                return extractFromType(v1.value0.value);
            };
            return Data_Maybe.Nothing.value;
        };
        return Data_Array.findMap(matchDecl)(v.decls);
    };
};
var extractPageType = function (declName) {
    return function (src) {
        var v = PureScript_CST.parseModule(src);
        if (v instanceof PureScript_CST.ParseSucceeded) {
            return findSignature(declName)(v.value0.body);
        };
        if (v instanceof PureScript_CST.ParseSucceededWithErrors) {
            return findSignature(declName)(v.value0.body);
        };
        if (v instanceof PureScript_CST.ParseFailed) {
            return Data_Maybe.Nothing.value;
        };
        throw new Error("Failed pattern match at Loader.Main (line 145, column 32 - line 148, column 27): " + [ v.constructor.name ]);
    };
};
var generateRoutePursFromModules = function (routes) {
    return function (modules) {
        var segmentParamType = function (v) {
            if (v instanceof CatchAll) {
                return " (Array String)";
            };
            if (v instanceof OptCatchAll) {
                return " (Array String)";
            };
            return " String";
        };
        var pageRoutes = Data_Array.filter(function (r) {
            return r.kind === "page";
        })(routes);
        var routeEntries = map1(function (route) {
            var src = Data_Maybe.maybe("")(function (v) {
                return v.source;
            })(lookup(route.mod)(modules));
            var segments = Data_Maybe.fromMaybe([  ])(extractPageType("page")(src));
            return new Data_Tuple.Tuple(route, segments);
        })(pageRoutes);
        var isParam = function (v) {
            if (v instanceof Dynamic) {
                return true;
            };
            if (v instanceof CatchAll) {
                return true;
            };
            if (v instanceof OptCatchAll) {
                return true;
            };
            return false;
        };
        var constructorName = function (modName) {
            var parts = Data_Array.drop(1)(Data_String_Common.split(".")(modName));
            var isIndex = eq3(parts)([ "Home" ]);
            if (isIndex) {
                return "Home";
            };
            return Data_String_Common.joinWith("__")(parts);
        };
        var constructorEntry = function (route) {
            return function (segments) {
                var name = constructorName(route.mod);
                var paramSegs = Data_Array.filter(isParam)(segments);
                var $303 = Data_Array.length(paramSegs) > 0;
                if ($303) {
                    return name + foldMap(segmentParamType)(paramSegs);
                };
                return name;
            };
        };
        var constructors = map1(function (v) {
            return constructorEntry(v.value0)(v.value1);
        })(routeEntries);
        var appendExpr = function (v) {
            return function (v1) {
                if (v === "") {
                    return v1;
                };
                return v + (" <> " + v1);
            };
        };
        var addSeg = function (v) {
            return function (v1) {
                if (v1 instanceof Static) {
                    return {
                        expr: appendExpr(v.expr)(show("/" + v1.value0)),
                        varIdx: v.varIdx
                    };
                };
                if (v1 instanceof Dynamic) {
                    var v2 = varName(v.varIdx);
                    return {
                        expr: appendExpr(v.expr)(show("/") + (" <> " + v2)),
                        varIdx: v.varIdx + 1 | 0
                    };
                };
                if (v1 instanceof CatchAll) {
                    var v2 = varName(v.varIdx);
                    return {
                        expr: appendExpr(v.expr)("foldMap (append " + (show("/") + (") " + v2))),
                        varIdx: v.varIdx + 1 | 0
                    };
                };
                if (v1 instanceof OptCatchAll) {
                    var v2 = varName(v.varIdx);
                    return {
                        expr: appendExpr(v.expr)("foldMap (append " + (show("/") + (") " + v2))),
                        varIdx: v.varIdx + 1 | 0
                    };
                };
                throw new Error("Failed pattern match at Loader.Main (line 750, column 3 - line 751, column 56): " + [ v.constructor.name, v1.constructor.name ]);
            };
        };
        var buildPathExpr = function (segments) {
            var v = foldl(addSeg)({
                expr: "",
                varIdx: 0
            })(segments);
            var $324 = Data_String_Common["null"](v.expr);
            if ($324) {
                return show("/");
            };
            return v.expr;
        };
        var caseEntry = function (route) {
            return function (segments) {
                var name = constructorName(route.mod);
                var paramSegs = Data_Array.filter(isParam)(segments);
                var vars = Data_Array.mapWithIndex(function (i) {
                    return function (v) {
                        return varName(i);
                    };
                })(paramSegs);
                var patVars = (function () {
                    var $326 = Data_Array["null"](vars);
                    if ($326) {
                        return "";
                    };
                    return " " + Data_String_Common.joinWith(" ")(vars);
                })();
                var pathExpr = buildPathExpr(segments);
                return "    " + (name + (patVars + (" -> " + pathExpr)));
            };
        };
        var cases = map1(function (v) {
            return caseEntry(v.value0)(v.value1);
        })(routeEntries);
        var allLines = append1([ pursMarker, "module Route where", "", "import Prelude", "import Next.Route (class IsRoute)", "", "data Route = " + Data_String_Common.joinWith(" | ")(constructors), "", "derive instance Eq Route", "derive instance Ord Route", "", "instance IsRoute Route where", "  toPath = case _ of" ])(append1(cases)([ "" ]));
        return Data_String_Common.joinWith("\x0a")(allLines);
    };
};
var detectKind = function (parts) {
    var v = Data_Array.head(parts);
    if (v instanceof Data_Maybe.Just && v.value0 === "Page") {
        return new Data_Maybe.Just("page");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "Layout") {
        return new Data_Maybe.Just("layout");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "Template") {
        return new Data_Maybe.Just("template");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "Loading") {
        return new Data_Maybe.Just("loading");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "ErrorBoundary") {
        return new Data_Maybe.Just("error");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "GlobalError") {
        return new Data_Maybe.Just("globalError");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "NotFound") {
        return new Data_Maybe.Just("notFound");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "Handler") {
        return new Data_Maybe.Just("handler");
    };
    if (v instanceof Data_Maybe.Just && v.value0 === "Default") {
        return new Data_Maybe.Just("default");
    };
    return Data_Maybe.Nothing.value;
};
var moduleToRoute = function (appDir) {
    return function (outputDir) {
        return function (info) {
            var parts = Data_String_Common.split(".")(info.name);
            var v = (function () {
                var v1 = Data_Array.head(parts);
                if (v1 instanceof Data_Maybe.Just && v1.value0 === "Slot") {
                    var v2 = Data_Array.index(parts)(1);
                    if (v2 instanceof Data_Maybe.Just) {
                        return new Data_Tuple.Tuple([ "@" + Data_String_Common.toLower(v2.value0) ], Data_Array.drop(2)(parts));
                    };
                    if (v2 instanceof Data_Maybe.Nothing) {
                        return new Data_Tuple.Tuple([  ], parts);
                    };
                    throw new Error("Failed pattern match at Loader.Main (line 371, column 24 - line 373, column 33): " + [ v2.constructor.name ]);
                };
                return new Data_Tuple.Tuple([  ], parts);
            })();
            return bind1((function () {
                var v1 = detectKind(v.value1);
                if (v1 instanceof Data_Maybe.Just) {
                    return new Data_Maybe.Just(v1.value0);
                };
                if (v1 instanceof Data_Maybe.Nothing) {
                    if (!Data_Array["null"](v.value0)) {
                        return new Data_Maybe.Just("page");
                    };
                    if (Data_Boolean.otherwise) {
                        return Data_Maybe.Nothing.value;
                    };
                };
                throw new Error("Failed pattern match at Loader.Main (line 377, column 11 - line 381, column 29): " + [ v1.constructor.name ]);
            })())(function (kind) {
                var hasExplicitKind = notEq1(detectKind(v.value1))(Data_Maybe.Nothing.value);
                var modParts = (function () {
                    if (hasExplicitKind) {
                        return Data_Array.drop(1)(v.value1);
                    };
                    return v.value1;
                })();
                var methods = (function () {
                    var $348 = kind === "handler";
                    if ($348) {
                        return findHandlerMethods(info.source);
                    };
                    return [  ];
                })();
                var declName = kindToDeclName(kind);
                var firstMethodDecl = Data_Array.head(methods);
                return bind1((function () {
                    var $349 = kind === "handler";
                    if ($349) {
                        if (firstMethodDecl instanceof Data_Maybe.Just) {
                            return extractPageType(firstMethodDecl.value0)(info.source);
                        };
                        if (firstMethodDecl instanceof Data_Maybe.Nothing) {
                            return Data_Maybe.Nothing.value;
                        };
                        throw new Error("Failed pattern match at Loader.Main (line 391, column 10 - line 393, column 25): " + [ firstMethodDecl.constructor.name ]);
                    };
                    return extractPageType(declName)(info.source);
                })())(function (segments) {
                    var nextPathSegs = segmentsToNextPath(segments);
                    var groupSegs = (function () {
                        var $352 = kind === "layout";
                        if ($352) {
                            return layoutPathSegments;
                        };
                        return modulePathSegments;
                    })()(modParts);
                    var routePath = foldl($foreign.joinPath)(foldl($foreign.joinPath)(foldl($foreign.joinPath)(appDir)(v.value0))(groupSegs))(nextPathSegs);
                    var ext = (function () {
                        var $353 = kind === "handler";
                        if ($353) {
                            return ".ts";
                        };
                        return ".tsx";
                    })();
                    var filePath = $foreign.joinPath(routePath)(kindToFileName(kind) + ext);
                    var outputModule = $foreign.joinPath(outputDir)(info.name + "/index.js");
                    var relImport = $foreign.relativePath(routePath)(outputModule);
                    var canHaveMeta = (kind === "page" || (kind === "layout" || kind === "template")) && notEq1(info.directive)(new Data_Maybe.Just("use client"));
                    var hasMetadata = canHaveMeta && hasMetadataDecl(info.source);
                    var hasViewport = canHaveMeta && hasViewportDecl(info.source);
                    var hasStaticParams = kind === "page" && hasStaticParamsDecl(info.source);
                    var routeConfigs = findRouteConfigDecls(info.source);
                    return new Data_Maybe.Just({
                        mod: info.name,
                        kind: kind,
                        filePath: filePath,
                        relImport: relImport,
                        routePath: routePath,
                        directive: info.directive,
                        hasMetadata: hasMetadata,
                        hasViewport: hasViewport,
                        hasStaticParams: hasStaticParams,
                        handlerMethods: methods,
                        routeConfigs: routeConfigs
                    });
                });
            });
        };
    };
};
var detectDirective = function (modName) {
    return function (src) {
        if (Data_Array.any((function () {
            var $368 = eq("-- @client");
            return function ($369) {
                return $368(Data_String_Common.trim($369));
            };
        })())(Data_String_Common.split("\x0a")(src))) {
            return new Data_Maybe.Just("use client");
        };
        if (Data_Array.any((function () {
            var $370 = eq("-- @server");
            return function ($371) {
                return $370(Data_String_Common.trim($371));
            };
        })())(Data_String_Common.split("\x0a")(src))) {
            return new Data_Maybe.Just("use server");
        };
        if (Data_String_CodeUnits.contains(".Client")(modName)) {
            return new Data_Maybe.Just("use client");
        };
        if (Data_String_CodeUnits.contains(".Server")(modName)) {
            return new Data_Maybe.Just("use server");
        };
        if (Data_String_CodeUnits.contains("Actions.")(modName)) {
            return new Data_Maybe.Just("use server");
        };
        if (Data_Boolean.otherwise) {
            return Data_Maybe.Nothing.value;
        };
        throw new Error("Failed pattern match at Loader.Main (line 107, column 1 - line 107, column 52): " + [ modName.constructor.name, src.constructor.name ]);
    };
};
var scanModules = function (srcDir) {
    var addModule = function (accEff) {
        return function (file) {
            return function __do() {
                var acc = accEff();
                var src = $foreign.readFileSync(file)();
                var v = extractModuleName(src);
                if (v instanceof Data_Maybe.Nothing) {
                    return acc;
                };
                if (v instanceof Data_Maybe.Just) {
                    var directive = detectDirective(v.value0)(src);
                    return insert(v.value0)({
                        name: v.value0,
                        source: src,
                        file: file,
                        directive: directive
                    })(acc);
                };
                throw new Error("Failed pattern match at Loader.Main (line 124, column 5 - line 128, column 74): " + [ v.constructor.name ]);
            };
        };
    };
    return function __do() {
        var files = findPursFiles(srcDir)();
        return foldl(addModule)(pure(Data_Map_Internal.empty))(files)();
    };
};
var computeRoutes = function (appDir) {
    return function (outputDir) {
        return function (modules) {
            return Data_Array.mapMaybe(function (v) {
                return moduleToRoute(appDir)(outputDir)(v.value1);
            })(toUnfoldable(modules));
        };
    };
};
var cleanStaleRoutes = function (appDir) {
    return function (currentRoutes) {
        var keepPaths = map1(function (v) {
            return v.filePath;
        })(currentRoutes);
        return removeStaleIn(appDir)(keepPaths);
    };
};
var cleanStaleOutput = function (outputDir) {
    return function __do() {
        var exists = $foreign.existsSync(outputDir)();
        return when(exists)(function __do() {
            var entries = $foreign.readdirSync(outputDir)();
            return for_(entries)(function (entry) {
                return when(entry.isDirectory)((function () {
                    var corefnPath = $foreign.joinPath($foreign.joinPath(outputDir)(entry.name))("corefn.json");
                    return function __do() {
                        var corefnExists = $foreign.existsSync(corefnPath)();
                        return when(corefnExists)(function __do() {
                            var content = $foreign.readFileSync(corefnPath)();
                            var v = extractJsonField("modulePath")(content);
                            if (v instanceof Data_Maybe.Just && Data_String_CodeUnits.contains("src/")(v.value0)) {
                                var srcExists = $foreign.existsSync(v.value0)();
                                return unless(srcExists)((function () {
                                    var full = $foreign.joinPath(outputDir)(entry.name);
                                    return function __do() {
                                        $foreign.rmSync(full)();
                                        return Effect_Console.log("[purescript-rsc] stale output removed: " + full)();
                                    };
                                })())();
                            };
                            return Data_Unit.unit;
                        })();
                    };
                })());
            })();
        })();
    };
};
var main = /* #__PURE__ */ (function () {
    var root = $foreign.getEnvOrDefault("PURESCRIPT_RSC_ROOT")(".");
    var srcDir = $foreign.resolvePath(root)("src");
    var appDir = $foreign.resolvePath(root)("app");
    var outputDir = $foreign.resolvePath(root)("output");
    return function __do() {
        var modules = scanModules(srcDir)();
        writeDirectivesManifest(outputDir)(modules)();
        cleanStaleOutput(outputDir)();
        var routes = computeRoutes(appDir)(outputDir)(modules);
        var routePurs = generateRoutePursFromModules(routes)(modules);
        var routeFile = $foreign.joinPath(srcDir)("Route.purs");
        var changed = writeIfChanged(routeFile)(routePurs)();
        (function () {
            if (changed) {
                return Effect_Console.log("[purescript-rsc] Generated src/Route.purs")();
            };
            return Effect_Console.log("[purescript-rsc] Route.purs unchanged")();
        })();
        cleanStaleRoutes(appDir)(routes)();
        var result = foldl(writeRouteFile)(pure({
            written: 0,
            skipped: 0
        }))(routes)();
        Effect_Console.log("[purescript-rsc] " + (show1(result.written) + (" written, " + (show1(result.skipped) + (" unchanged, " + (show1(Data_Array.length(routes)) + " total route(s)"))))))();
        var v = lookup("Middleware")(modules);
        if (v instanceof Data_Maybe.Just) {
            var middlewarePath = $foreign.resolvePath(root)("middleware.ts");
            var content = generateMiddleware(outputDir)(v.value0);
            var middlewareChanged = writeIfChanged(middlewarePath)(content)();
            return when(middlewareChanged)(Effect_Console.log("[purescript-rsc] Generated middleware.ts"))();
        };
        if (v instanceof Data_Maybe.Nothing) {
            return Data_Unit.unit;
        };
        throw new Error("Failed pattern match at Loader.Main (line 624, column 3 - line 631, column 25): " + [ v.constructor.name ]);
    };
})();
export {
    readFileSync,
    writeFileSync,
    existsSync,
    mkdirSync,
    readdirSync,
    unlinkSync,
    rmSync,
    relativePath,
    joinPath,
    resolvePath,
    getEnvOrDefault
} from "./foreign.js";
export {
    Static,
    Dynamic,
    CatchAll,
    OptCatchAll,
    marker,
    pursMarker,
    findPursFiles,
    detectDirective,
    scanModules,
    extractModuleName,
    extractPageType,
    findSignature,
    extractFromType,
    walkTypeArg,
    walkOpChain,
    typeToSegment,
    markLastDynamic,
    markLastCatchAll,
    markLastOptCatchAll,
    hasMetadataDecl,
    hasMetaSig,
    hasStaticParamsDecl,
    hasStaticParamsSig,
    hasViewportDecl,
    hasViewportSig,
    handlerMethodNames,
    findHandlerMethods,
    findMethods,
    routeConfigNames,
    findRouteConfigDecls,
    findConfigs,
    isJsReserved,
    methodToExportName,
    segmentsToNextPath,
    computeRoutes,
    modulePathSegments,
    layoutPathSegments,
    kindToFileName,
    kindToDeclName,
    detectKind,
    moduleToRoute,
    generateTsx,
    varNames,
    varName,
    cleanStaleRoutes,
    removeStaleIn,
    cleanStaleOutput,
    extractJsonField,
    writeIfChanged,
    main,
    generateMiddleware,
    hasConfigDecl,
    hasConfigSig,
    writeDirectivesManifest,
    writeRouteFile,
    generateRoutePursFromModules,
    eqSegment,
    showSegment
};
//# sourceMappingURL=index.js.map
