// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import _default from "../output/Default.Root/index.js";
export default async function(props) {
  const render = await _default();
  const params = {...await (props.params ?? {})};
  const searchParams = {...await (props.searchParams ?? {})};
  return render({ params, searchParams });
}
