// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { get, post, put, delete_, patch, head_, options } from "../../../output/Handler.Api.Hello/index.js";
export async function GET(request, context) {
  const params = await (context.params ?? {});
  return get()(request, params);
}
export async function POST(request, context) {
  const params = await (context.params ?? {});
  return post()(request, params);
}
export async function PUT(request, context) {
  const params = await (context.params ?? {});
  return put()(request, params);
}
export async function DELETE(request, context) {
  const params = await (context.params ?? {});
  return delete_()(request, params);
}
export async function PATCH(request, context) {
  const params = await (context.params ?? {});
  return patch()(request, params);
}
export async function HEAD(request, context) {
  const params = await (context.params ?? {});
  return head_()(request, params);
}
export async function OPTIONS(request, context) {
  const params = await (context.params ?? {});
  return options()(request, params);
}
