// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
export { get as GET, post as POST, put as PUT, delete_ as DELETE, patch as PATCH, head_ as HEAD, options as OPTIONS } from "../../../output/Handler.Api.Hello/index.js";
