"use client";
// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { page } from "../output/Page.Home/index.js";
import { use, useRef, Suspense } from "react";
function Inner(props) { const ref = useRef(null); if (!ref.current) ref.current = page(props); return use(ref.current); }
export default function(props) { return <Suspense><Inner {...props} /></Suspense>; }
