"use client";
// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { globalError } from "../output/GlobalError.Root/index.js";
export default await globalError();
