// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { layout, metadata } from "../output/Layout.Root/index.js";
export default async function(props) {
  const render = await layout();
  return render(props);
}
export async function generateMetadata(props) {
  const meta = await metadata();
  return meta(props);
}
