// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { layout as mk } from "../output/Layout.Root/index.js";
export default async function(props) {
  const render = await mk();
  return render(props);
}
