"use client";
// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { page } from "../../output/Page.Optimistic/index.js";
import { use } from "react";
const _Component = await page();
export default function(props) {
  const params = {...use(props.params)};
  const searchParams = {...use(props.searchParams)};
  return _Component({ params, searchParams });
}
