// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { page, metadata } from "../../output/Page.Media/index.js";
export default async function(props) {
  const render = await page();
  const params = await (props.params ?? {});
  const searchParams = await (props.searchParams ?? {});
  return render({ params, searchParams });
}
export async function generateMetadata(props) {
  const meta = await metadata();
  const params = await (props.params ?? {});
  const searchParams = await (props.searchParams ?? {});
  return meta({ params, searchParams });
}
