// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { middleware, config } from "examples/kitchen-sink/output/Middleware/index.js";
export { middleware, config };
