// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
export { page as default, metadata as generateMetadata, staticParams as generateStaticParams } from "../../../output/Page.Blog.Slug/index.js";
