-- @generated by purescript-rsc -- do not edit
module Route where

import Prelude

data Route = About | Blog__Slug String | Dashboard | Home

derive instance Eq Route
derive instance Ord Route

toPath :: Route -> String
toPath = case _ of
  About -> "/about"
  Blog__Slug a -> "/blog" <> "/" <> a
  Dashboard -> "/dashboard"
  Home -> "/"
