-- @generated by purescript-rsc -- do not edit
module Route where

import Prelude

data Route = About | Home | Dashboard | Blog__

derive instance Eq Route
derive instance Ord Route

toPath :: Route -> String
toPath = case _ of
  About -> "/about"
  Home -> "/"
  Dashboard -> "/dashboard"
  Blog__ -> "/blog/"
