// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { get, post } from "../../../output/Handler.Api.Demo/index.js";
export async function GET(request, context) {
  const params = await (context.params ?? {});
  return get()(request, params);
}
export async function POST(request, context) {
  const params = await (context.params ?? {});
  return post()(request, params);
}
