// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { layout } from "../../output/Layout.Dashboard/index.js";
export default async function(props) {
  const render = await layout();
  return render(props);
}
