// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { loading } from "../../output/Loading.Dashboard/index.js";
export default async function() {
  return loading()
}
