"use client";
// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { loading as mk } from "../../output/Loading.Dashboard/index.js";
export default await mk();
