// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { page as mk } from "../../output/Page.Dashboard/index.js";
export default async function(props) {
  const render = await mk();
  const params = await (props.params ?? {});
  const searchParams = await (props.searchParams ?? {});
  return render({ params, searchParams });
}
