// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { page as mk } from "../../output/Pages.Dashboard/index.js";
export default async function(props) {
  const render = await mk();
  return render(props);
}
