// @generated by purescript-rsc — do not edit
// @ts-expect-error — PureScript output
import { template } from "../../output/Template.Dashboard/index.js";
export default async function(props) {
  const render = await template();
  return render(props);
}
